# Generated by Django 5.2.6 on 2025-09-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.PositiveIntegerField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('expertise_domains', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
