# Generated by Django 5.2.6 on 2025-09-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.FileField(upload_to='materials/'),
        ),
    ]
