# Generated by Django 5.2.6 on 2025-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_materials',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='core.material'),
        ),
    ]
