# Generated by Django 5.2.6 on 2025-10-05 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.course'),
        ),
    ]
