# Generated by Django 5.2.6 on 2025-10-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_schedule_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='core.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
    ]
