# Generated by Django 5.2.6 on 2025-10-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_course_unique_together_college_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='courses',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.college'),
        ),
    ]
