# Generated by Django 5.2.6 on 2025-10-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_college_courses_alter_schedule_college'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.college'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'college', 'name')},
        ),
    ]
