# Generated by Django 5.2.6 on 2025-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_batch_unique_together_batch_college_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='core.course'),
        ),
    ]
