# Generated by Django 5.2.6 on 2025-10-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_batch_unique_together_college_courses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'name')},
        ),
        migrations.RemoveField(
            model_name='college',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.college'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('college', 'name')},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='college',
        ),
    ]
