# Generated by Django 5.2.6 on 2025-10-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_course_unique_together_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.college'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('college', 'name')},
        ),
    ]
