# Generated by Django 5.2.6 on 2025-10-06 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_course_unique_together_college_courses_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.college'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'name', 'college')},
        ),
    ]
