# Generated by Django 5.2.6 on 2025-10-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_material_course_alter_schedule_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='college',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.AddField(
            model_name='schedule',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.batch'),
        ),
    ]
