# Generated by Django 5.2.6 on 2025-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_schedule_college_remove_schedule_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.batch'),
        ),
    ]
