# Generated by Django 5.2.6 on 2025-10-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_course_image_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
