# Generated by Django 5.2.6 on 2025-10-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_course_image_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course')),
                ('materials', models.ManyToManyField(blank=True, related_name='modules', to='core.material')),
            ],
            options={
                'ordering': ['module_number'],
                'unique_together': {('course', 'module_number')},
            },
        ),
    ]
