# Generated by Django 5.2.6 on 2025-10-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the material in minutes.'),
        ),
    ]
