# Generated by Django 5.2.6 on 2025-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_material_duration_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
    ]
