# Generated by Django 5.2.6 on 2025-10-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_employee_alter_user_role_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TRAINER', 'Trainer'), ('STUDENT', 'Student')], default='ADMIN', max_length=10),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
