# Generated by Django 5.2.6 on 2025-10-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_bill_trainer_alter_schedule_trainer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeApplication',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TRAINER', 'Trainer'), ('STUDENT', 'Student')], default='ADMIN', max_length=10),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
