# Generated by Django 5.2.6 on 2025-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional summary or bio', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, help_text='Education, degrees, and certifications', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_history',
            field=models.TextField(blank=True, help_text='Detailed experience, achievements, and work history', null=True),
        ),
    ]
