# Generated by Django 5.2.6 on 2025-11-01 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_user_bio_user_education_user_work_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., B.E. in Computer Science or SSLC', max_length=200)),
                ('institute', models.CharField(help_text='e.g., K S School Of Engineering And Management', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_ongoing', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('academic_performance', models.TextField(blank=True, help_text='e.g., 7.67 CGPA or 84.96%', null=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
