# Generated by Django 5.2.6 on 2025-11-01 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_user_education_educationentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_history',
        ),
        migrations.CreateModel(
            name='WorkExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Software Engineer', max_length=200)),
                ('institute', models.CharField(help_text='e.g., Google, Microsoft', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_ongoing', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Describe your role, responsibilities, and achievements', null=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
