# Generated by Django 5.2.6 on 2025-11-01 15:04

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_user_work_history_workexperienceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., AWS Certified Cloud Practitioner', max_length=200)),
                ('institute', models.CharField(help_text='e.g., Amazon Web Services', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Issue Date')),
                ('end_date', models.DateField(blank=True, help_text='Expiry Date', null=True)),
                ('currently_ongoing', models.BooleanField(default=False, help_text='Mark if this certification does not expire')),
                ('description', models.TextField(blank=True, help_text='Add any other details', null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=core.models.employee_certificate_path)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='certification_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
