# Generated by Django 5.2.6 on 2025-11-08 08:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationentry',
            name='marksheet_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.employee_marksheet_path),
        ),
    ]
